version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_oficina
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dboficina
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_oficina
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8081:80"
    depends_on:
      - db
