version: '3.8'
services:
  app:
    build: .
    image: proyecto-oficina
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=dboficina
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dboficina
    ports:
      - "3306:3306"
